- name: Bare Metal
  slug: bare-metal
  description: Bare Metal Hosting
  icon: material-server

- name: Instances
  slug: instance
  description: Virtual Machines
  icon: material-server

- name: GPU
  slug: gpu
  description: GPU
  icon: material-server

- name: Domain Registration
  slug: domain
  description: Domain Registration
  icon: material-earth

- name: DNS
  slug: dns
  description: Domain Name System
  icon: material-earth

- name: Email
  slug: email
  description: Email Account Services (SMTP, IMAP)
  icon: material-email

- name: Transactional Email
  slug: transactional-email
  description: Transactional Email Service API
  icon: material-email-fast

- name: Container Registry
  slug: container-registry
  description: Container Registry
  icon: simple-docker

- name: Managed Databases
  slug: database
  description: Managed Databases (PostgreSQL, MySQL, Redis, MongoDB)
  icon: material-database

- name: Load Balancers
  slug: load-balancer
  description: Managed Load Balancers
  icon: material-earth

- name: Kubernetes
  slug: kubernetes
  description: Manged Kubernetes Cluster
  icon: simple-kubernetes

- name: Object Storage
  slug: object-storage
  description: S3 Compatible Object Storage
  icon: fontawesome-solid-bucket

- name: CDN
  slug: cdn
  description: Content Delivery Network
  icon: material-earth

- name: Analytics
  slug: analytics
  description: Web Analytics Services
  icon: material-chart-bar

- name: Monitoring
  slug: monitoring
  description: Service Monitoring and Alerting
  icon: material-server

- name: VPN
  slug: vpn
  description: Virtual Private Servers
  icon: material-lock

- name: Terraform Provider
  slug: terraform
  description: Terraform Provider
  icon: simple-terraform

